---
{{- range $name, $data := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{- range $key, $value := $data }}
  {{ $key }}: |-
    {{ $value | nindent 8 }}
  {{- end }}
---
{{- end }}
