{{- if .Values.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "revealjs.fullname" . }}-config
data:
  {{- range $fileName, $fileContent := .Values.configMap.presentations }}
  {{ $fileName }}: |-
    {{ $fileContent | nindent 8 }}
  {{- end }}
{{- end }}