---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "revealjs.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "revealjs.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "revealjs.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: confd-volume
              mountPath: /etc/nginx/conf.d
            {{- if .Values.configMap.enabled }}
            - name: config-volume
              mountPath: /usr/share/nginx/html/slides
            {{- end }}
            {{- range .Values.existingConfigMaps }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: nginx-conf
        - name: confd-volume
          configMap:
            name: nginx-confd
        {{- if .Values.configMap.enabled }}
        - name: config-volume
          configMap:
            name: {{ include "revealjs.fullname" . }}-config
        {{- end }}
        {{- range .Values.existingConfigMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}